language: python
sudo: false
python:
- '3.5'
install:
- pip install -r requirements.txt
script:
- mkdir logs
- touch logs/realestate.log
- nosetests tests --with-coverage
- tox
after_success:
- coveralls
deploy:
  provider: s3
  access_key_id: AKIAIWQKYAETOQ2N7CBQ
  secret_access_key:
    secure: Dh/dAklShJFyeh8jMTMe05BM20r///zb66k6f1VbwN26OrbWV1V6p4Ue83N1jTpFvBFc2C/XTHi/r42jRJU5H+zlJBc3Rwsly7aqHPXxee207Zi3Kgo62cqaZSLV4mnNlineFAkdjM82OhV1TKnT843F5L6gaSPJJHVRtz5Vrbk=
  bucket: lensnola
  local-dir: www/static
  upload-dir: realestate
  acl: public_read
  on:
    repo: TheLens/realestate
