language: python
sudo: false
python:
- '2.7'
install:
- pip install -r requirements.txt
before_script:
- export PYTHONPATH=$PYTHONPATH:$(pwd)
- aws s3 sync realestate/static s3://lensnola/realestate/ --acl public-read
script:
- coverage run tests/test*.py
after_success:
- aws s3 sync realestate/static s3://lensnola/realestate/ --acl public-read
- coveralls
env:
  global:
  - secure: awpJDjhV6F0TeuxfeMGk3FgUPTlz6ABTgWrW/QcPUS/TbKBwbv25LNOS4uasGZhuevWfPGykhLVqo1moqI8ucbns8LiRO1v/+YGnOTQ3+iWU2IXXn/822ygAJqDyk0FeUGpUdbXKgmKQAfj1UFFC8U2ybaddJ5C4x9moY1n15bg=
  - secure: ff9wi9V9wQH63tgGc0YXkc5bZe+SPtYPh5cJC3JRmAMJWrg+6ZJ9F9xq0f+urvTjodg2gCHIyc7Oob+OIQ4AumcGusgrku5xGsF1i3mRZVxf83CN7RKJEVKpGyAr23jBBYhiWJKi3hXiKzY7gVP6VwQWG7nO2C+mEnD7DmH0Hx8=
  - secure: KCsJzOF3MOMh9Koxi+goC0PRhWCWmrgRe5bl9JYGy/cVjNvs+AdE9jSJO5lPLZudjq9SloI2sWNt6KqAVfQoFoTvhV2Frchg8/WJ4drci4k0oAbBh56gEm9FsMcTWivbnYyJBIrJZuLhmTk/qGuui99P8uMJR3zC4VP/DzbGwpw=
  - secure: uk0SD0CSD3RRRQ6oe+pdp0IRagLAJi+EcbRgv2GqwesbX8br4jS9fDE5jewwhp4bw/tG8mSz946OSzPsqlgfwRhIxNo0WMnfUmMdfY6iiZJvv7lLEik7Ctw4Y6oFTTQZnTh+HStpT0CU1My8OpjAN07CWjmhzTXoGpmwentr9Pk=
  - secure: Jf3JVz7pZXuIL7i/7e0XTdND9Cfs4t8zvUuNpTPln7WOjLdV5yLIL/JcGP3I5i+WOIYUHUYAe+DZO7wU8xEs+f6QtWHJw6+vKkqSJNhpEl920YF2yqoSphaxEOW7I6cSQF/75lIJgaHiv0R6S8sZJs2NpJIK9UMr0Dk63HzGhZE=
  - secure: RdY4joije3vk/Rs1NCoxd26dKcKHsDDRA3aivgxtF6aG/TikzLtmK99oes19MwTrwvSXAWiwiMuEWxlpCgP/ZPtLxM/0nuuwsbpaNbKDeH3iyIY29tHo4t+GTgt8AyB+TKmMv2JzS6zO7sSs3TC2+np+zn+h+weWs6lmtL/KPnI=
  - secure: E1b0v77zdZK87xOcL0Ty9gZ6HeWKUkB/P0DbxpjIe82wPQjs54P0sbI20KMZ77cHBoNFqrMtySCXKVE64gk6i3/4JNxyNm9Qf3VYq0OhsXdIGz0uSOoZd4bB7IoyqkjB0B39ZAiJpMPtzLv3FIZCbIGVr7h7nSHfqIcWo6JMq9o=
  - secure: EfdZqoDT/XmZ5misGa2lo76TKzqT49hrkGr7eSERKwGPX6CXOgwBHM+9+xw1I0by0768AmH1WJdo0AAn8Hkd7diZRDvTn1/ls327qfQn4NT0oAzBy8/MZNwYnkPoAllThFaPOriZmRfaUq4HWiC1e5x/KGtu/K2IoH/DmOlgc0U=
  - secure: Y8lVKrLZd0IXN8RTuZTZPxvTajrSZUTKVHA7tPHtxD82GS+GumxLr6ja3mYwsDIvuqNZfYUlZoNa+LpIgcJ74Tq9wR8ZBjGgI/JzDMW+bMxIa0Cz2jp/cD03d/R8KaFJ7xD9Mi4IXJqxvt4qQ9torFVAloYAYoh1Q9JeWz6lTXw=
  - secure: iN/Nk29uq832aWmgMlf3KLq0xFNcSTnlwBSv3vdjFphncm2el645i6XKTS3wGYNUrYaUfvClF62mOzr4SE2T7R+VpZV9OKMk6kFNUG2FNmlf7QjcxIkCLyhDQlhsu3fEfPTA/deZh48Y7tM2QNrFyeXX/Wqt5fH1W3AnsCvB/4o=
  - secure: hw/GhivbEnO/No/gJuUcBLkn+kUk9u92ERVLx3QrzEK5wNjf+hFIAY7RxVa2E6mkBJQodA4b9o9w69JxUsid+TJA62zWiobNdoXaGNguI5/eErsE90XZCpmXokPeiLn5CMHJQwiw9VA9JXOeshex35h0EC8gEnyRFXG2NhnupOI=
  - secure: l9KtlZ8hcGQxNfJI0jDen2+ZoLI0KfuGo6O762pa8RbnOhAvPm7jcYqtYn3dPNQmF/QZ2jS6dBR7RQOqtYKLFPWsbED13OB7Y2ke9yMv54yxOySQSfxz2uvfPummMq/n+I9jbH7wSVP/bzz0ou+is7Vn3DkCG966YHkU4RO1NTs=
  - secure: rjYT14F7sj1SlRFR50tEMGfnWdfl3XsygVxdHmc3jddOehkaAVRYcDd5cTrdCIdQZnIaj08mSYi1Z1Gh7gR7uEh9zdGf78Zw8xlCg+G5Tmi9YgX/1hldTYioouaz3UUXpwGUvjYTf9Vs5FYENt7uUzMmkeRIcQkPqLVsQvgFCLc=
  - secure: jyhz0UJDzYQF5Yj14Hs8PJVKIZi5JaFoZZiGUvKG6OR1+NJhTK7HqTIco4+8ZNqgzTooFphe/xVyTTkWe1zoceqZyS6tSw8AaTmexY7TSYJWOXQzMwF+WYbVCX6NioYSd6+gqaXqQLvUKjpN8RPFTf9XTXyhnmJ5j7QrZhy/LlI=
  - secure: jZKIaKtUxzoeMWZzNfK7PZ62pwky+kn3UTfyTJ/6W8+V3vyeB4p1oq+nOPjYke3tVuYBpVELJnFWy8QmFLfu8O8NNh1EdZLCa7Mz5M6epPMMOa5DX4sWlXcN31fajgncparPdzUNK5Q+qzsx3p4xvbZy0JYrQQmfqFcUy/dJKz8=
