language: python
sudo: false
python:
- '2.7'
install:
- pip install -r requirements.txt
before_script:
- export PYTHONPATH=$PYTHONPATH:$(pwd)
- aws s3 sync realestate/static s3://lensnola/realestate/ --acl public-read
script:
- coverage run tests/test*.py
after_success:
- aws s3 sync realestate/static s3://lensnola/realestate/ --acl public-read
- coveralls
env:
  matrix:
  - secure: JO1ND+N4zA5s4JiC78wQPqB3aj120dZ0BsSkGDxrcITPczPh2RySpHNfPicCRAQMp/E1D5ynL7qW7P6SThRdlQkGsLy3R235WkCy57AzSIwvvwGBMCUnfNrnP74+PjQ3+mEBmnqQktirK63F5wrZu5RhSnOufMQ0MUK7qH6OzGA=
  - secure: ZS2TNOsVSVywWn9g9u/RnpYOpqNGGBIs1aPglQck9eLmWc+3+GI89eeC1RogKLeeEgZlP7uaO7L4reV2l5XGjAUmVHCUcvxCUHuEnKuh5KxuGv60twQV3ujvVZceM1dYSwr2qTuxdPw/UoZqC/PRv7tnXfnkrx+M4lrTZeC4x+Q=
  - secure: g6c77XqMYAx+EqdkeejfyZLjSvupWgGbkdC02325tskCwS1nCXou7Qld1FZXnFUS141rLBKUavqZAzqGWPgaP4kwbsa9HYcN1tFpmIVj0eBb1szfWfqX8+tiIbBJT2BiNHlhpHZrSRBabNcItGK1DkjxtYwZxzgnL5Yfh8lHq84=
  - secure: pt0yUu7OSsjGuNSa1CUOYCaHdyE85/OigWWpPs1ayPdyvcqSA50zag9m9mh6gp4PKWf0PeNYxGmLHaJzSbw/bciVhZAtxqquBziy4cdls40WZCx/9sPZ/vxhyfw8Iho0s8EcXrjy2XO5oUp9wt72nIb1zxTby2FhCiOYbvRSYFw=
  - secure: C+w73yEH3s1HkStNA9gOv3afuHjhmOAKQYdz81jGXsrodnbI/ystDA+LQNg+1yklnNPDCjE0NeIR242kWnO8tX+gzCQNP0IsBl+TpS+hFLPBmTctxqAbAutK6C1JsV4wKKzariskYTXFxeP0n+OHUclW9LqOwTjT41KhAyZ9ano=
  - secure: CCaFbDg+ne7fDqeKBZ2yPw32Ma4HJOcgo6ZzyR/qVkk56CUlNHVPfDYVnqLjLu1Q9tqlaJuCXOzg8EXq/OY5dZD3lu7IqB0hW1wpYbn7MhadWeG/IW5sgkXUaPwKkJWGVBulLf8pItIiuXfRD+uG09/AkQ/oQaXI4PabXQfcFT8=
  - secure: fiqI85TIkVpNloVhZtggUjK4fAmUrNg6LJNsMBRJMu/TvPFo7l8CSY4Lv1gZzyQUPoeJ0RjmwfKQh0lxe0yK5dliqQPULzmZgSnTXuM9TnBF/XTIXNXE36hVvbCDm8SpUafeAoSzj99HvuV8ETEhDVnGg7OTspy81MV3jcCiHks=
  - secure: UpYaK0J7DHTkcuTA6IM5VP5vH/IscWAZn5qB9Dbwq4yBDGNXwdEHsP9SXxJ7oK2ekZ7zIMG5abSoD8X4FS84HOH/grtaEVIDeRxPHnTgwrXyKxHpBTQuH4p14BaOmigmZXGLuadFfHJYuJFrxeoYiGrWrYboRX4jnS6htDuGwg0=
  - secure: PTQdPrFOJfxe3MPg9GwsftclSRzIpL/QqW2slTGvIJrCBcso6kchalfbHTyJNNDHjvtLQwX5inPAS+TPICyuxS9RKhzXDCfeqoLwonlIHJvoVrZx/vzJgBPSzdPPq5TCPF/zK5K1Tg64EKXyLBVBDCjcAA+47dtiIWQALKUuQC0=
  - secure: phsbZ21gkNMg/RjtXtOuGTzvU1AElRI49V3nkMNZg+m3W+YH8xpGZ7aCLWc51B3HdTdNiBHHmZoUvWW8stMQZ1sW+DDjkXHNrVzQZO/FUZFHfaaB9cYIIVRECgGVW5gI1ukTXgPKjEI14nIU4eTBOc7EVW4XaVEChgOBmtTMvQI=
  - secure: jKEf+cVeyGoMpQA8DRZNx4iTQHydXcwMPqFz6eQ5lG5mU8r6ONgkJyP8GQcPKtngtblNyrqXKsRXiMPfuOd/UssRf+yWAOFlMCxv1NieT6wKOkBkjNgUgRs4s+4WOiprcSmBS0c0Ja0lh1xXxLZOrBgL7W6RfuqSaWRCpeOP3M8=
  - secure: TUp+n10ClozrDnU1oY5HuvPfdwfH49Td5lSl7QCGQj6TIARcHFz4o7JHKga2mVmZ0XNj1Cjvqr6IuY6kFA1tj/fHnMG91FvyEVFP6U7mhjHZeUYnz4Fek22KSa5WgDT/zpy9GHy78iiP+ix3yzOPleX2BjWntB5zLNZx/XMcrF4=
  - secure: Y5rp1iRLTLEgkuw1eHyfSwJSuSsUD55W7LPWxeJC0Cg75Be+JZqXIMtafi//soGLx6hrm08r3ktcWRkp+3qLmxsmH3AQs4G+gSj/bo7QIKdST8WMhJQunBHPJ/vL+IyDYYLSPRvlSD3f8xZQXqGc7Qm+oR6n54EyWYjgS28aRpI=
  - secure: OgCRZ0LStYlpvQyzhRid6rGbuPb1YtR5hVwOqfREDWDwUWRqiOEsUS5iSOOQh0ig5F88DyNXNNEOuu/NIo2lJjS4UtYcJzfDVEfLX3l7DImeD2eOh/GNyf6d2P7VSHACZIRj6DjHT4MEJizhjxZ2HoCc1un8uACRYvdnNlIKeBU=
  - secure: AsTaLHoa82P/qm8r9TCkgq8VXdxblIzguFxbi2TKSJ511or7PAzybAFIKMkI3gJiId7D4nqVL3+wa57FFZyTqH9RyaWi+tHQTgPU7LmCrjUg+4Fa6CS1QXK4vJRE4bCLsXVoL9rvTADVqBW5iHQtX4029DIQQ+KfG3ipUxPuVec=
