language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
script:
- nosetests tests/test*.py
before_install:
- openssl aes-256-cbc -K $encrypted_7e1cf468a927_key -iv $encrypted_7e1cf468a927_iv
  -in landrecords/config.py.enc -out landrecords/config.py -d
